/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.database.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class AddEmployee extends javax.swing.JFrame {

    MyHashTable table;

    /**
     * Creates new form AddEmployee
     *
     * @param t
     */
    
    // constructor
    public AddEmployee(MyHashTable t) {
        initComponents();
        table = t;

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        employeeNumberText = new javax.swing.JTextField();
        annualSalaryText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        deductionRateText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        maleRadioButton = new javax.swing.JRadioButton();
        otherRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        workLocationComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Annual Salary");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 190, 60));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 70));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Work Location");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 180, 60));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Sex");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 60));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Deduction Rate");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 170, 50));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Last Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, 60));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Add Full-Time Employee");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 410, 40));

        employeeNumberText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        employeeNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNumberTextActionPerformed(evt);
            }
        });
        getContentPane().add(employeeNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, 40));

        annualSalaryText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(annualSalaryText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 140, 40));

        lastNameText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(lastNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 140, 40));

        deductionRateText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(deductionRateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 140, 40));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Employee Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, 60));

        firstNameText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(firstNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 140, 40));

        AddButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        AddButton.setText("Add Employee");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 210, 50));

        genderGroup.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        maleRadioButton.setSelected(true);
        maleRadioButton.setText("Male");
        getContentPane().add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        genderGroup.add(otherRadioButton);
        otherRadioButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        otherRadioButton.setText("Other");
        getContentPane().add(otherRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        genderGroup.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        femaleRadioButton.setText("Female");
        femaleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRadioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(femaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        workLocationComboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        workLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mississauga", "Brampton", "Caledon", "Ottawa" }));
        getContentPane().add(workLocationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNumberTextActionPerformed


    // get all the info of full time employee from text fields and add data into hash table
    
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

        final int typeOfEmployee = 0;
        String firstName = firstNameText.getText();
        String lastName = lastNameText.getText();
        String deductionRateString = deductionRateText.getText();
        String annualSalaryString = annualSalaryText.getText();
        String employeeNumberString = employeeNumberText.getText();
        if (firstName.isEmpty() || lastName.isEmpty() || deductionRateString.isEmpty() || annualSalaryString.isEmpty() || employeeNumberString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill All Data Properly!");
        } else {
            int employeeNumber = 0;
            try {
                employeeNumber = Integer.parseInt(employeeNumberText.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Invalid Employee Number");
                return;
            }

            int sex;
            if (maleRadioButton.isSelected()) {
                sex = 0;
            } else if (femaleRadioButton.isSelected()) {
                sex = 1;
            } else { //otherRadioButton is selected 
                sex = 2;
            }

            int workLocation;
            if (workLocationComboBox.getSelectedItem().toString().equals("Mississauga")) {
                workLocation = 0;
            } else if (workLocationComboBox.getSelectedItem().toString().equals("Brampton")) {
                workLocation = 1;
            } else if (workLocationComboBox.getSelectedItem().toString().equals("Caledon")) {
                workLocation = 2;
            } else { //selected Ottawa
                workLocation = 3;
            }

            double deductionRate;
            try {
                deductionRate = Double.parseDouble(deductionRateText.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Invalid Deduction Rate");
                return;
            }

            double annualSalary;
            try {
                annualSalary = Double.parseDouble(annualSalaryText.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Invalid Annual Salary");
                return;
            }
            int location = table.searchEmployee(employeeNumber);
            if (location == -1) {
                FullTimeEmployee employee1 = new FullTimeEmployee(employeeNumber, firstName, lastName, sex, workLocation, deductionRate, annualSalary, typeOfEmployee);
                table.addEmployee(employee1);
                table.displayContents();
                JOptionPane.showMessageDialog(this, "Employee Added Successfully");
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Employee Number Already Exists!");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed

    private void femaleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRadioButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField annualSalaryText;
    private javax.swing.JTextField deductionRateText;
    private javax.swing.JTextField employeeNumberText;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField firstNameText;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JComboBox<String> workLocationComboBox;
    // End of variables declaration//GEN-END:variables
}
