/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.database.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class AddPartTimeEmployee extends javax.swing.JFrame {

    static MyHashTable table;

    /**
     * Creates new form AddPartTimeEmployee
     */
    public AddPartTimeEmployee(MyHashTable t) {
        initComponents();
        table = t;

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hourlyWageText = new javax.swing.JTextField();
        hoursPerWeekText = new javax.swing.JTextField();
        weeksPerYearText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        employeeNumberText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        deductionRateText = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        maleRadioButton = new javax.swing.JRadioButton();
        otherRadioButton = new javax.swing.JRadioButton();
        fds = new javax.swing.JRadioButton();
        workLocationComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Hourly Wage");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 140, 40));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("Weeks Per Year");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 170, 70));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("Hours Per Week");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 170, 50));

        hourlyWageText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(hourlyWageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 120, 40));

        hoursPerWeekText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        hoursPerWeekText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursPerWeekTextActionPerformed(evt);
            }
        });
        getContentPane().add(hoursPerWeekText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 120, 40));

        weeksPerYearText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        weeksPerYearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeksPerYearTextActionPerformed(evt);
            }
        });
        getContentPane().add(weeksPerYearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 120, 40));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("Add Part-Time Employee");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 370, 40));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Employee Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 170, 60));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 110, 70));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Work Location");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 160, 60));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Sex");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 249, 80, 60));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Deduction Rate");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 150, 50));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Last Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 199, 130, 60));

        employeeNumberText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        employeeNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeNumberTextActionPerformed(evt);
            }
        });
        getContentPane().add(employeeNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 120, 40));

        firstNameText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(firstNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 169, 120, 40));

        lastNameText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(lastNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 219, 120, 40));

        deductionRateText.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(deductionRateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 120, 40));

        AddButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        AddButton.setText("Add Employee");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 190, 50));

        genderButtonGroup.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        maleRadioButton.setSelected(true);
        maleRadioButton.setText("Male");
        getContentPane().add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 110, -1));

        genderButtonGroup.add(otherRadioButton);
        otherRadioButton.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        otherRadioButton.setText("Other");
        getContentPane().add(otherRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 110, -1));

        genderButtonGroup.add(fds);
        fds.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        fds.setText("Female");
        getContentPane().add(fds, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 100, -1));

        workLocationComboBox.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        workLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mississauga", "Brampton", "Caledon", "Ottawa" }));
        getContentPane().add(workLocationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weeksPerYearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeksPerYearTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weeksPerYearTextActionPerformed

    private void hoursPerWeekTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursPerWeekTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursPerWeekTextActionPerformed

    private void employeeNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeNumberTextActionPerformed

    // get all the info of part time employee from text fields and add data into hash table
    
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

        final int typeOfEmployee = 1;
        String firstName = firstNameText.getText();
        String lastName = lastNameText.getText();
        String deductionRateString = deductionRateText.getText();
        String hourlyWageString = hourlyWageText.getText();
        String hoursPerWeekString = hoursPerWeekText.getText();
        String weeksPerYearString = weeksPerYearText.getText();
        String employeeNumberString = employeeNumberText.getText();
        if (firstName.isEmpty() || lastName.isEmpty() || deductionRateString.isEmpty() || hourlyWageString.isEmpty() || hoursPerWeekString.isEmpty() || weeksPerYearString.isEmpty() || employeeNumberString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill All Data Properly!");
        } else {
            int employeeNumber = 0;
            try {
                employeeNumber = Integer.parseInt(employeeNumberText.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Invalid Employee Number");
                return;
            }
            int sex;
            if (maleRadioButton.isSelected()) {
                fds.setSelected(false);
                otherRadioButton.setSelected(false);
                sex = 0;
            } else if (fds.isSelected()) {
                maleRadioButton.setSelected(false);
                otherRadioButton.setSelected(false);
                sex = 1;
            } else {
                maleRadioButton.setSelected(false);
                fds.setSelected(false);
                sex = 2;
            }

            int workLocation;
            if (workLocationComboBox.getSelectedItem() == "Mississauga") {
                workLocation = 0;
            } else if (workLocationComboBox.getSelectedItem() == "Brampton") {
                workLocation = 1;
            } else if (workLocationComboBox.getSelectedItem() == "Caledon") {
                workLocation = 2;
            } else {
                workLocation = 3;
            }

            double deductionRate;
            try {
                deductionRate = Double.parseDouble(deductionRateText.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Invalid Deduction Rate");
                return;
            }

            double hourlyWage;
            int hoursPerWeek, weeksPerYear;
            try {
                hourlyWage = Double.parseDouble(hourlyWageText.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Invalid Hourly Wage");
                return;
            }

            try {
                hoursPerWeek = Integer.parseInt(hoursPerWeekText.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Invalid Hours per Week");
                return;
            }

            try {
                weeksPerYear = Integer.parseInt(weeksPerYearText.getText());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Invalid Weeks Per Year");
                return;
            }
            int location = table.searchEmployee(employeeNumber);
            if (location == -1) {
                PartTimeEmployee employee1;
                employee1 = new PartTimeEmployee(employeeNumber, firstName, lastName, sex,
                        workLocation, deductionRate, hourlyWage, hoursPerWeek, weeksPerYear, typeOfEmployee);
                table.addEmployee(employee1);
                table.displayContents();
                JOptionPane.showMessageDialog(this, "Employee Added Successfully");
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Employee Number Already Exists!");
            }
        }
    }//GEN-LAST:event_AddButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField deductionRateText;
    private javax.swing.JTextField employeeNumberText;
    private javax.swing.JRadioButton fds;
    private javax.swing.JTextField firstNameText;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JTextField hourlyWageText;
    private javax.swing.JTextField hoursPerWeekText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JTextField weeksPerYearText;
    private javax.swing.JComboBox<String> workLocationComboBox;
    // End of variables declaration//GEN-END:variables
}
