/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.database.project;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class OpenDatabase extends javax.swing.JFrame {

    static MyHashTable table;
//static CreateNewDatabase nDb;

    /**
     * Creates new form CreateNewDatabase
     * @param t
     */
    public OpenDatabase(MyHashTable t) {
        initComponents();
        table = t;
        SearchEmployeePanel.setVisible(false);
        partTimeEmployeePanel.setVisible(false);
        fullTimeEmployeePanel.setVisible(false);

        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchEmployeePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        searchEmployeeNumberText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        annualGrossIncomeOutputLabel = new javax.swing.JLabel();
        employeeNumberOutputLabel = new javax.swing.JLabel();
        firstNameOutputLabel = new javax.swing.JLabel();
        sexOutputLabel = new javax.swing.JLabel();
        workLocationOutputLabel = new javax.swing.JLabel();
        deductionRateOutputLabel = new javax.swing.JLabel();
        typeOfEmployeeOutputLabel = new javax.swing.JLabel();
        lastNameOutputLabel = new javax.swing.JLabel();
        fullTimeEmployeePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        annualSalaryOutputLabel = new javax.swing.JLabel();
        partTimeEmployeePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        weeksPerYearOutputLabel = new javax.swing.JLabel();
        hourlyWageOutputLabel = new javax.swing.JLabel();
        hoursPerWeekOutputLabel = new javax.swing.JLabel();
        employeeDatabasePanel = new javax.swing.JPanel();
        addFullTimeEmployee = new javax.swing.JButton();
        addPartTimeEmployee = new javax.swing.JButton();
        searchEmployee = new javax.swing.JButton();
        saveDatabase = new javax.swing.JButton();
        removeEmployeeButton = new javax.swing.JButton();
        listEmployees = new javax.swing.JButton();
        modifyEmployeeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchEmployeePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Enter the Employee Number :");
        SearchEmployeePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 40));
        SearchEmployeePanel.add(searchEmployeeNumberText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 160, 30));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        SearchEmployeePanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 80, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Annual Gross Income $");
        SearchEmployeePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 190, 60));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("First Name");
        SearchEmployeePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 70));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Work Location");
        SearchEmployeePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 140, 60));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("Sex");
        SearchEmployeePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 60));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setText("Deduction Rate");
        SearchEmployeePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, 50));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setText("Last Name");
        SearchEmployeePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 150, 60));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setLabelFor(annualSalaryOutputLabel);
        jLabel10.setText("Type of Employee");
        SearchEmployeePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 190, 60));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel15.setText("Employee Number");
        SearchEmployeePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 60));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        SearchEmployeePanel.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 80, 30));

        annualGrossIncomeOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchEmployeePanel.add(annualGrossIncomeOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 130, 30));

        employeeNumberOutputLabel.setBackground(new java.awt.Color(255, 255, 255));
        employeeNumberOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchEmployeePanel.add(employeeNumberOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 30));

        firstNameOutputLabel.setBackground(new java.awt.Color(255, 255, 255));
        firstNameOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchEmployeePanel.add(firstNameOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, 30));

        sexOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchEmployeePanel.add(sexOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 130, 30));

        workLocationOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchEmployeePanel.add(workLocationOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 130, 30));

        deductionRateOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchEmployeePanel.add(deductionRateOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 130, 30));

        typeOfEmployeeOutputLabel.setBackground(new java.awt.Color(255, 255, 255));
        typeOfEmployeeOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchEmployeePanel.add(typeOfEmployeeOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 130, 30));

        lastNameOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SearchEmployeePanel.add(lastNameOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, 30));

        fullTimeEmployeePanel.setBorder(new javax.swing.border.MatteBorder(null));
        fullTimeEmployeePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel14.setText("Annual Salary");
        fullTimeEmployeePanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 60));

        annualSalaryOutputLabel.setBackground(new java.awt.Color(255, 255, 255));
        annualSalaryOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fullTimeEmployeePanel.add(annualSalaryOutputLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 30));

        SearchEmployeePanel.add(fullTimeEmployeePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 290, 220));

        partTimeEmployeePanel.setBorder(new javax.swing.border.MatteBorder(null));
        partTimeEmployeePanel.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel11.setText("Hourly Wage");
        partTimeEmployeePanel.add(jLabel11);
        jLabel11.setBounds(10, 70, 160, 40);

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel13.setText("Hours Per Week");
        partTimeEmployeePanel.add(jLabel13);
        jLabel13.setBounds(10, 120, 190, 50);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel12.setText("Weeks Per Year");
        partTimeEmployeePanel.add(jLabel12);
        jLabel12.setBounds(10, 160, 190, 70);

        weeksPerYearOutputLabel.setBackground(new java.awt.Color(255, 255, 255));
        weeksPerYearOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        partTimeEmployeePanel.add(weeksPerYearOutputLabel);
        weeksPerYearOutputLabel.setBounds(150, 180, 130, 30);

        hourlyWageOutputLabel.setBackground(new java.awt.Color(255, 255, 255));
        hourlyWageOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        partTimeEmployeePanel.add(hourlyWageOutputLabel);
        hourlyWageOutputLabel.setBounds(150, 70, 130, 30);

        hoursPerWeekOutputLabel.setBackground(new java.awt.Color(255, 255, 255));
        hoursPerWeekOutputLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        partTimeEmployeePanel.add(hoursPerWeekOutputLabel);
        hoursPerWeekOutputLabel.setBounds(150, 130, 130, 30);

        SearchEmployeePanel.add(partTimeEmployeePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 290, 220));

        getContentPane().add(SearchEmployeePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 510));

        employeeDatabasePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addFullTimeEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addFullTimeEmployee.setText("Add Full Time Employee");
        addFullTimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFullTimeEmployeeActionPerformed(evt);
            }
        });
        employeeDatabasePanel.add(addFullTimeEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 230, 40));

        addPartTimeEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addPartTimeEmployee.setText("Add Part Time Employee");
        addPartTimeEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPartTimeEmployeeActionPerformed(evt);
            }
        });
        employeeDatabasePanel.add(addPartTimeEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 230, 40));

        searchEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchEmployee.setText("Search Employee");
        searchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmployeeActionPerformed(evt);
            }
        });
        employeeDatabasePanel.add(searchEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 230, 40));

        saveDatabase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveDatabase.setText("Save Database");
        saveDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDatabaseActionPerformed(evt);
            }
        });
        employeeDatabasePanel.add(saveDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 230, 40));

        removeEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeEmployeeButton.setText("Remove Employee");
        removeEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeButtonActionPerformed(evt);
            }
        });
        employeeDatabasePanel.add(removeEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 230, 40));

        listEmployees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        listEmployees.setText("List all Employees");
        listEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listEmployeesActionPerformed(evt);
            }
        });
        employeeDatabasePanel.add(listEmployees, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 230, 40));

        modifyEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifyEmployeeButton.setText("Modify Employee");
        modifyEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyEmployeeButtonActionPerformed(evt);
            }
        });
        employeeDatabasePanel.add(modifyEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 230, 40));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Database");
        employeeDatabasePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 460, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee.database.project.images/EMP_Database.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        employeeDatabasePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 510));

        getContentPane().add(employeeDatabasePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEmployeeButtonActionPerformed

        new RemoveFrame(table).setVisible(true);
    }//GEN-LAST:event_removeEmployeeButtonActionPerformed

    private void listEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listEmployeesActionPerformed
        new ShowAllFrame(table).setVisible(true);
    }//GEN-LAST:event_listEmployeesActionPerformed

    private void saveDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDatabaseActionPerformed

        MyHashTable.writeToFile();
        JOptionPane.showMessageDialog(this, "Database Saved!");
    }//GEN-LAST:event_saveDatabaseActionPerformed

    private void searchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmployeeActionPerformed

        SearchEmployeePanel.setVisible(true);
        employeeDatabasePanel.setVisible(false);


    }//GEN-LAST:event_searchEmployeeActionPerformed

    private void addFullTimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFullTimeEmployeeActionPerformed
        AddEmployee aE = new AddEmployee(table);
        aE.setVisible(true);

    }//GEN-LAST:event_addFullTimeEmployeeActionPerformed

    private void addPartTimeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPartTimeEmployeeActionPerformed
        AddPartTimeEmployee pE = new AddPartTimeEmployee(table);
        pE.setVisible(true);

    }//GEN-LAST:event_addPartTimeEmployeeActionPerformed
//method to clear all text fields when required

    void clearAllFields() {
        typeOfEmployeeOutputLabel.setText("");
        employeeNumberOutputLabel.setText("");
        firstNameOutputLabel.setText("");
        lastNameOutputLabel.setText("");
        sexOutputLabel.setText("");
        workLocationOutputLabel.setText("");
        deductionRateOutputLabel.setText("");
        hourlyWageOutputLabel.setText("");
        hoursPerWeekOutputLabel.setText("");
        weeksPerYearOutputLabel.setText("");
        annualSalaryOutputLabel.setText("");
        annualGrossIncomeOutputLabel.setText("");
        searchEmployeeNumberText.setText("");
    }
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String number = searchEmployeeNumberText.getText();
        if (!number.isEmpty()){
        try {
            int empNum = Integer.parseInt(number);
        int location;
        location = table.searchEmployee(empNum);
        if (location != -1) {
            EmployeeInfo tempEmployee = table.getEmployeeInfo(location, empNum);

            if (tempEmployee instanceof FullTimeEmployee) {
//Casting FullTimeEmployee 
                FullTimeEmployee employee;
                employee = (FullTimeEmployee) table.getEmployeeInfo(location, empNum);

                String fN = employee.getFirstName();
                String lN = employee.getLastName();
                int empNumber;
                empNumber = employee.getEmployeeNumber();
                int sex = employee.getSex();
                int workLocation = employee.getWorkLocation();
                double dedRate;
                dedRate = employee.getDeductionRate();
                double annualSalary;
                annualSalary = employee.getAnnualSalary();
                String gender;
                if (sex == 0) {
                    gender = "male";
                } else if (sex == 1) {
                    gender = "female";
                } else {
                    gender = "Other";
                }
                String place;
                if (workLocation == 0) {
                    place = "Mississauga";
                } else if (workLocation == 1) {
                    place = "Brampton";
                } else if (workLocation == 2) {
                    place = "Caledon";
                } else {
                    place = "Ottawa";
                }
                FullTimeEmployee fEmployee = new FullTimeEmployee();
                double annualGrossIncome = fEmployee.calcAnnualGrossIncome(annualSalary);
                String annualGrossIncomeString = String.format("%.2f",annualGrossIncome);
                partTimeEmployeePanel.setVisible(false);
                fullTimeEmployeePanel.setVisible(true);

                typeOfEmployeeOutputLabel.setText("FullTime");
                employeeNumberOutputLabel.setText(Integer.toString(empNumber));
                firstNameOutputLabel.setText(fN);
                lastNameOutputLabel.setText(lN);
                sexOutputLabel.setText(gender);
                workLocationOutputLabel.setText(place);
                deductionRateOutputLabel.setText((Double.toString(dedRate)) + "%");
                annualSalaryOutputLabel.setText("$" + (Double.toString(annualSalary)));
                annualGrossIncomeOutputLabel.setText(annualGrossIncomeString);

            } else if (tempEmployee instanceof PartTimeEmployee) {
                //Casting PartTimeEmployee 
                PartTimeEmployee employee = (PartTimeEmployee) table.getEmployeeInfo(location, empNum);

                String fN = employee.getFirstName();
                String lN = employee.getLastName();
                int empNumber;
                empNumber = employee.getEmployeeNumber();
                int sex = employee.getSex();
                int workLocation = employee.getWorkLocation();
                double dedRate;
                dedRate = employee.getDeductionRate();
                double hourlyWage;
                hourlyWage = employee.getHourlyWage();
                int hoursPerWeek;
                hoursPerWeek = employee.getHoursPerWeek();
                int weeksPerYear;
                weeksPerYear = employee.getWeeksPerYear();
                String gender;
                if (sex == 0) {
                    gender = "male";
                } else if (sex == 1) {
                    gender = "female";
                } else {
                    gender = "Other";
                }
                String place;
                if (workLocation == 0) {
                    place = "Mississauga";
                } else if (workLocation == 1) {
                    place = "Brampton";
                } else if (workLocation == 2) {
                    place = "Caledon";
                } else {
                    place = "Ottawa";
                }
                PartTimeEmployee pEmployee = new PartTimeEmployee();
                double annualGrossIncome = pEmployee.calcAnnualGrossIncome(hourlyWage, hoursPerWeek, weeksPerYear);
                String annualGrossIncomeString = String.format("%.2f",annualGrossIncome);
                fullTimeEmployeePanel.setVisible(false);
                partTimeEmployeePanel.setVisible(true);

                typeOfEmployeeOutputLabel.setText("Part Time");
                employeeNumberOutputLabel.setText(Integer.toString(empNumber));
                firstNameOutputLabel.setText(fN);
                lastNameOutputLabel.setText(lN);
                sexOutputLabel.setText(gender);
                workLocationOutputLabel.setText(place);
                deductionRateOutputLabel.setText((Double.toString(dedRate)) + "%");
                hourlyWageOutputLabel.setText("$" + (Double.toString(hourlyWage)));
                hoursPerWeekOutputLabel.setText((Integer.toString(hoursPerWeek)));
                weeksPerYearOutputLabel.setText(Integer.toString(weeksPerYear));
                annualGrossIncomeOutputLabel.setText(annualGrossIncomeString);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Employee Not Found");
            clearAllFields();
        }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter an Integer value!");
        }
        }
        else {
            JOptionPane.showMessageDialog(this, "Enter a value!");
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        clearAllFields();
        SearchEmployeePanel.setVisible(false);
        employeeDatabasePanel.setVisible(true);

    }//GEN-LAST:event_backButtonActionPerformed

    private void modifyEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyEmployeeButtonActionPerformed

        ModifyJFrame updateFrame = new ModifyJFrame(table);
        updateFrame.setVisible(true);


    }//GEN-LAST:event_modifyEmployeeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SearchEmployeePanel;
    private javax.swing.JButton addFullTimeEmployee;
    private javax.swing.JButton addPartTimeEmployee;
    private javax.swing.JLabel annualGrossIncomeOutputLabel;
    private javax.swing.JLabel annualSalaryOutputLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel deductionRateOutputLabel;
    private javax.swing.JPanel employeeDatabasePanel;
    private javax.swing.JLabel employeeNumberOutputLabel;
    private javax.swing.JLabel firstNameOutputLabel;
    private javax.swing.JPanel fullTimeEmployeePanel;
    private javax.swing.JLabel hourlyWageOutputLabel;
    private javax.swing.JLabel hoursPerWeekOutputLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lastNameOutputLabel;
    private javax.swing.JButton listEmployees;
    private javax.swing.JButton modifyEmployeeButton;
    private javax.swing.JPanel partTimeEmployeePanel;
    private javax.swing.JButton removeEmployeeButton;
    private javax.swing.JButton saveDatabase;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchEmployee;
    private javax.swing.JTextField searchEmployeeNumberText;
    private javax.swing.JLabel sexOutputLabel;
    private javax.swing.JLabel typeOfEmployeeOutputLabel;
    private javax.swing.JLabel weeksPerYearOutputLabel;
    private javax.swing.JLabel workLocationOutputLabel;
    // End of variables declaration//GEN-END:variables
}
